# My makefile
SKETCH = $(shell dirname $(realpath $(firstword $(MAKEFILE_LIST))))/NodeMCU_ledflash.ino 

UPLOAD_PORT = /dev/tty.usbserial-0001
BOARD = esp8266

include $(HOME)/makeEspArduino/makeEspArduino.mk
